name: Scheduled Trigger Go CI

on:
  #pull_request:
  #  branches:
  #    - main
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '0 0 * * *' # every day at midnight for UTC

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
        check-latest: false
        cache: false

    - name: Install dependencies and build
      run: go mod download -x

    - name: Build
      run: go build -o crawler crawler.go

    - name: Run
      run: go run .

    - name: Check if files were updated
      id: check_files
      run: |
        # Check if there are any changes to commit
        git add data.csv data.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
          echo "should_commit=false" >> $GITHUB_OUTPUT
        else
          echo "Files updated, ready to commit"
          echo "should_commit=true" >> $GITHUB_OUTPUT
        fi

    - name: Deploy
      if: steps.check_files.outputs.should_commit == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        commit_message: "upd: data updated"
        file_pattern: "data.json data.csv"
